/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx_spi_driver.h"

#define DELAY_TIME		500000
#define USER_BUTTON_PIN GPIO_PIN_NO_0

SPI_Handle_t SPI2Handle;
volatile uint8_t flag = 0;
// char name[] = "MANUEL";
uint16_t name[] = {0x4D41, 0x4E55, 0x454C}; // MANUEL in 16-bit format

void SPI2_GPIOInits(void);
void SPI2_Inits(void);
void GPIO_ButtonInit(void);
void delay(void);

int main(void) {
    // Initialize button and SPI
    GPIO_ButtonInit();
    SPI2_GPIOInits();
    SPI2_Inits();

    // Enable the SPI peripheral
    SPI_SSIConfig(SPI2, ENABLE); // Set NSS high internally
    SPI_PeripheralControl(SPI2, ENABLE);

    while(1) {
        if (flag) {
            flag = 0;  // Clear the flag
            SPI_Send(SPI2, (uint8_t*)name, strlen(name));
        }
    }

    return 0;
}

void GPIO_ButtonInit(void) {
    GPIO_Handle_t GPIOBtn;

    // GPIO Button Configuration
    GPIOBtn.pGPIOx = GPIOA;
    GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = USER_BUTTON_PIN;
    GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
    GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

    GPIO_Init(&GPIOBtn);

    // IRQ Configurations
    GPIO_IRQ_ProrityConfig(IRQ_NO_EXTI0, IRQ_PRI_NO_15);
    GPIO_IRQConfig(IRQ_NO_EXTI0, ENABLE);
}

void SPI2_GPIOInits(void) {
    GPIO_Handle_t SPIPins;

    // SPI2 peripheral
    SPIPins.pGPIOx = GPIOB;
    SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_ALTFN_5;
    SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
    SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    // SCLK
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
    GPIO_Init(&SPIPins);

    // MOSI
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
    GPIO_Init(&SPIPins);
}

void SPI2_Inits(void) {
    SPI2Handle.pSPIx = SPI2;
    SPI2Handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
    SPI2Handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
    SPI2Handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8; // Generating SCLK of 2MHz
    SPI2Handle.SPIConfig.SPI_DFF = SPI_DFF_16_BITS;
    SPI2Handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
    SPI2Handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
    SPI2Handle.SPIConfig.SPI_SSM = SPI_SSM_EN; // Software slave management enabled

    SPI_Init(&SPI2Handle);
}

void EXTI0_IRQHandler(void) {
	delay();
    GPIO_IRQHandling(USER_BUTTON_PIN);
    flag = 1;
}

void delay(void) {
    for (uint32_t i = 0; i < 500000; i++);
}
